Repository prgrms-aibe-devcourse/AIBE1-Project2-Team07-Backend, pull requests merged in 2025-05, with the labels that each got.

#34 ci: dev 브랜치 관련 워크플로우 및 파일 업데이트
  .github/workflows/build_image.yml
  .github/workflows/main.yml
  .github/workflows/slack_notification.yml
  .github/workflows/test.yml
  .github/workflows/webhook.yml
  jenkins/Jenkinsfile
  src/main/resources/application-dev.yml
Labels: 🧹 기타 작업, 🚨 긴급

#36 chore: 워크플로우 빌드 수정
  .github/workflows/main.yml
  docker/Dockerfile
  jenkins/Jenkinsfile
Labels: 🧹 기타 작업

#30 feat:훈련사#8 자격 신청(파일업로드 아직)
  src/main/java/org/lucky0111/pettalk/controller/trainer/TrainerController.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/CertificationRequestDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerApplicationRequestDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Certification.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Trainer.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerService.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#37 feat: 로그인, 회원가입 #9
  src/main/java/org/lucky0111/pettalk/config/auth/CustomSuccessHandler.java
  src/main/java/org/lucky0111/pettalk/config/auth/SecurityConfig.java
  src/main/java/org/lucky0111/pettalk/config/auth/SwaggerConfig.java
  src/main/java/org/lucky0111/pettalk/controller/auth/AuthController.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/KakaoResponse.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/LoginDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/NaverResponse.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/OAuthTempTokenDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/TokenDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/TokenRequest.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/TokenRequestDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/UserRegistrationDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/user/ProfileUpdateDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/chat/Chat.java
  src/main/java/org/lucky0111/pettalk/domain/entity/chat/Chatroom.java
  src/main/java/org/lucky0111/pettalk/service/auth/ResponseService.java
  src/main/java/org/lucky0111/pettalk/service/user/UserService.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTFilter.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTTokenManager.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTTokenProvider.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTUtil.java
  src/main/java/org/lucky0111/pettalk/util/auth/OAuth2UserServiceHelper.java
  src/main/resources/application-dev.yml
Labels: 🛠️ 백엔드, 🌟 기능 추가, ♻️ 리팩터링, 🚨 긴급

#43 fix: swagger mixed content 이슈 해결
  src/main/java/org/lucky0111/pettalk/config/auth/SwaggerConfig.java
  src/main/resources/application-dev.yml
Labels: 🐛 버그, 🚨 긴급

#45 Feature/trainer
  src/main/java/org/lucky0111/pettalk/controller/auth/AuthController.java
  src/main/java/org/lucky0111/pettalk/domain/common/UserRole.java
  src/main/java/org/lucky0111/pettalk/domain/dto/review/ReviewStatsDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/CertificationDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/user/PetUser.java
  src/main/java/org/lucky0111/pettalk/exception/CustomException.java
  src/main/java/org/lucky0111/pettalk/service/auth/CustomOAuth2UserService.java
  src/main/java/org/lucky0111/pettalk/service/file/FileUploaderService.java
  src/main/java/org/lucky0111/pettalk/service/file/FileUploaderServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTTokenManager.java
Labels: 🛠️ 백엔드

#52 Feature/trainer
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerPhotoDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerServiceFeeDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Trainer.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/TrainerPhoto.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/TrainerServiceFee.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/TrainerServiceFeeType.java
  src/main/java/org/lucky0111/pettalk/repository/trainer/TrainerPhotoRepository.java
  src/main/java/org/lucky0111/pettalk/repository/trainer/TrainerServiceFeeRepository.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#56 refactor: 소셜 로그인, JWT 리팩터링
  src/main/java/org/lucky0111/pettalk/config/auth/CustomSuccessHandler.java
  src/main/java/org/lucky0111/pettalk/config/auth/JWTConfig.java
  src/main/java/org/lucky0111/pettalk/config/auth/SecurityConfig.java
  src/main/java/org/lucky0111/pettalk/config/auth/SwaggerConfig.java
  src/main/java/org/lucky0111/pettalk/config/auth/TokenCleanupScheduler.java
  src/main/java/org/lucky0111/pettalk/controller/auth/AuthController.java
  src/main/java/org/lucky0111/pettalk/domain/common/AccountStatus.java
  src/main/java/org/lucky0111/pettalk/domain/common/OAuth2Provider.java
  src/main/java/org/lucky0111/pettalk/domain/common/TokenStatus.java
  src/main/java/org/lucky0111/pettalk/domain/common/TokenType.java
  src/main/java/org/lucky0111/pettalk/domain/common/UserRole.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/CustomOAuth2User.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/KakaoOAuth2UserInfo.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/KakaoResponse.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/LoginDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/NaverOAuth2UserInfo.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/NaverResponse.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/OAuth2Response.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/OAuth2UserInfo.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/OAuthTempTokenDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/TokenDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/TokenRequestDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/auth/UserRegistrationDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/user/UserDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/user/UserRegisterDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/user/UserResponseDTO.java
  src/main/java/org/lucky0111/pettalk/handler/OAuth2LoginFailureHandler.java
  src/main/java/org/lucky0111/pettalk/handler/OAuth2LoginSuccessHandler.java
  src/main/java/org/lucky0111/pettalk/repository/auth/RefreshTokenRepository.java
  src/main/java/org/lucky0111/pettalk/repository/user/PetUserRepository.java
  src/main/java/org/lucky0111/pettalk/service/auth/CustomOAuth2UserService.java
  src/main/java/org/lucky0111/pettalk/service/auth/JwtTokenProvider.java
  src/main/java/org/lucky0111/pettalk/service/auth/ResponseService.java
  src/main/java/org/lucky0111/pettalk/service/community/CommentServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/user/UserService.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTFilter.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTTokenManager.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTTokenProvider.java
  src/main/java/org/lucky0111/pettalk/util/auth/JWTUtil.java
  src/main/java/org/lucky0111/pettalk/util/auth/JwtFilter.java
  src/main/java/org/lucky0111/pettalk/util/auth/JwtUtil.java
  src/main/java/org/lucky0111/pettalk/util/auth/OAuth2UserInfoFactory.java
  src/main/java/org/lucky0111/pettalk/util/auth/OAuth2UserInfoFactoryImpl.java
  src/main/java/org/lucky0111/pettalk/util/auth/OAuth2UserServiceHelper.java
  src/main/java/org/lucky0111/pettalk/util/auth/PreOAuth2AuthenticationFilter.java
  src/main/resources/application-dev.yml
Labels: ♻️ 리팩터링, 🚨 긴급

#61 feat: MCP
  build.gradle
  src/main/java/org/lucky0111/pettalk/assistants/McpUserAssistant.java
  src/main/java/org/lucky0111/pettalk/config/mcp/McpAssistantConfig.java
  src/main/java/org/lucky0111/pettalk/controller/llm/McpChatController.java
  src/main/java/org/lucky0111/pettalk/service/llm/McpService.java
  src/main/java/org/lucky0111/pettalk/service/llm/McpServiceImpl.java
  src/main/resources/application-dev.yml
Labels: 🛠️ 백엔드, 🌟 기능 추가, ⏳ 보통

#67 feat: S3 연동, 파일 업로드 구현
  build.gradle
  src/main/java/org/lucky0111/pettalk/config/aws/S3Config.java
  src/main/java/org/lucky0111/pettalk/controller/trainer/TrainerController.java
  src/main/java/org/lucky0111/pettalk/service/file/FileUploaderService.java
  src/main/java/org/lucky0111/pettalk/service/file/FileUploaderServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#70 매칭 리팩토링
  src/main/java/org/lucky0111/pettalk/controller/match/UserApplyController.java
  src/main/java/org/lucky0111/pettalk/domain/dto/match/UserApplyRequestDTO.java
  src/main/java/org/lucky0111/pettalk/service/match/UserApplyServiceImpl.java
Labels: ♻️ 리팩터링

#77 Feature/trainer v2
  src/main/java/org/lucky0111/pettalk/controller/trainer/TrainerController.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/CertificationDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerApplicationRequestDTO.java
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerDTO.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerService.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#81 Feature/trainer v2
  src/main/java/org/lucky0111/pettalk/domain/dto/trainer/TrainerDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Trainer.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#85 feat: 태그, 훈련사 지역 검색 기능 추가, 챗봇 커뮤니티 검색 기능 추가, 프롬프트 수정
  src/main/java/org/lucky0111/pettalk/assistants/McpTagAssistant.java
  src/main/java/org/lucky0111/pettalk/assistants/McpUserAssistant.java
  src/main/java/org/lucky0111/pettalk/config/mcp/McpAssistantConfig.java
  src/main/java/org/lucky0111/pettalk/controller/mcp/McpChatController.java
  src/main/java/org/lucky0111/pettalk/service/file/FileUploaderServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpService.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/review/ReviewServiceImpl.java
Labels: 🛠️ 백엔드, 🌟 기능 추가, ⏳ 보통

#89 관리자 승인/거절 부분 rejected 추가
  src/main/java/org/lucky0111/pettalk/domain/dto/admin/AdminCertificationDTO.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Certification.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
Labels: 🛠️ 백엔드, 🐛 버그

#90 fix: 프롬프트 수정
  src/main/java/org/lucky0111/pettalk/assistants/McpTagAssistant.java
  src/main/java/org/lucky0111/pettalk/assistants/McpUserAssistant.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
Labels: 🛠️ 백엔드, ⏳ 보통

#91 fix: 훈련사 승인, 거절 역할 변경, ROLE 접근 제한
  src/main/java/org/lucky0111/pettalk/config/auth/SecurityConfig.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
Labels: 🛠️ 백엔드, 🐛 버그, ⏳ 보통

#93 fix: AdminPostDTO 수정
  src/main/java/org/lucky0111/pettalk/domain/dto/admin/AdminPostDTO.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
Labels: 🐛 버그, ⏳ 보통

#94 fix: 승인시 trainer ApprovedAt 설정
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
Labels: 🛠️ 백엔드, ⏳ 보통

#97 Feature/trainer v2
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/TrainerTagRelation.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🛠️ 백엔드

#98 fix: 프롬프트 수정
  src/main/java/org/lucky0111/pettalk/assistants/McpTagAssistant.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
  src/main/resources/application-dev.yml
Labels: 🐛 버그, ⏳ 보통

#99 fix: Duplicate entry 수정
  src/main/java/org/lucky0111/pettalk/config/auth/SecurityConfig.java
  src/main/java/org/lucky0111/pettalk/repository/trainer/TrainerTagRepository.java
  src/main/java/org/lucky0111/pettalk/service/trainer/TrainerServiceImpl.java
Labels: 🐛 버그

#102 fix: LLM 게시글 태그 생성 파라미터 변경
  src/main/java/org/lucky0111/pettalk/controller/mcp/McpChatController.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpService.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
Labels: 🛠️ 백엔드, 🐛 버그

#104 관리자 api 오류 수정
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
Labels: 🐛 버그

#106 fix: 프롬프트 수정
  src/main/java/org/lucky0111/pettalk/assistants/McpModerationAssistant.java
  src/main/resources/application-dev.yml
Labels: 🛠️ 백엔드, 🐛 버그

#112 fix: 프롬프트 수정
  src/main/java/org/lucky0111/pettalk/assistants/McpModerationAssistant.java
  src/main/java/org/lucky0111/pettalk/assistants/McpUserAssistant.java
  src/main/java/org/lucky0111/pettalk/service/mcp/McpServiceImpl.java
Labels: 🛠️ 백엔드, 🐛 버그, ⏳ 보통

#116 refactor: 유저 엔티티 setter 개선
  src/main/java/org/lucky0111/pettalk/domain/entity/user/PetUser.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/auth/CustomOAuth2UserService.java
  src/main/java/org/lucky0111/pettalk/service/user/UserService.java
Labels: 🛠️ 백엔드, ♻️ 리팩터링

#117 refactor: JWT 예외처리 개선
  src/main/java/org/lucky0111/pettalk/handler/OAuth2LoginSuccessHandler.java
  src/main/java/org/lucky0111/pettalk/service/auth/AuthServiceImpl.java
  src/main/java/org/lucky0111/pettalk/service/auth/CustomOAuth2UserService.java
  src/main/java/org/lucky0111/pettalk/service/auth/JwtTokenService.java
  src/main/java/org/lucky0111/pettalk/util/auth/JwtUtil.java
Labels: 🛠️ 백엔드, ♻️ 리팩터링

#118 refactor: 관리자 트랜잭션/setter 개선 및 입력 유효성 검증
  src/main/java/org/lucky0111/pettalk/controller/admin/AdminController.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Certification.java
  src/main/java/org/lucky0111/pettalk/domain/entity/trainer/Trainer.java
  src/main/java/org/lucky0111/pettalk/service/admin/AdminServiceImpl.java
Labels: 🛠️ 백엔드, ♻️ 리팩터링
